### ISSUE TITLE
Extended & archived components

### ISSUE THREAD

**Issue by vapoto** [CDFER/JLCPCB-Kicad-Library#8]
First of all thank you very much for this project, it is an incredible time saver when designing a PCB for production by JLCPCB!

I was using the vertical USB-C connector with 14 pins (C2982529), but this seems to have been moved to the archived components in the library. I assume this is because it is an extended part? However, there is also a JLCPCB-Extended (sub)library in this project. Could you explain how the selection for this is done?

It would be great to have all extended parts available (maybe in a separate folder/library), but I understand this might not be feasible because of computational and API limits. Would there be a way though for users to specify a list of extended parts and locally create a library for them in the same way as you are doing?

**Comment by CDFER** [comment]
To address your question about the USB-C connector (C2982529): JLCPCB occasionally changes which components are categorized as basic/preferred. For example, C2982529 was moved to the extended parts list on December 2nd ([see here](https://github.com/CDFER/jlcpcb-parts-database/blob/d7e695b20299d4b0330be322caf139cecf7c7b28/scraped/ComponentList.csv?plain=1#L891C1-L891C30)).

Currently, the library moves components that are no longer basic/preferred to the archive folder, along with their footprints and 3D models. If you're still looking for this part, you can find it [here](https://github.com/CDFER/JLCPCB-Kicad-Library/blob/main/Archived-Symbols-Footprints/JLCPCB-Kicad-Symbols/2982529.kicad_sym).

Regarding the "JLCPCB-Extended" sublibrary, it currently includes extended parts that I commonly use. However, adding all 300,000+ components isn’t feasible as KiCad wouldn’t handle that many symbols well, and there are no stock/price updates for extended components at the moment. That said, I may eventually integrate the most popular 1,000 or so extended components based on how quickly stock data decreases.

Unfortunately, generating symbols/footprints fully automatically isn’t possible yet, as I do a lot of manual reworks to improve quality (source EasyEDA files are often less than ideal). Adding user-specified components would require improvements to pull data directly from the SQLite file (which I’m considering for the future).

For now, if there are specific extended components you'd think would be useful, let me know and I'll do my best to add them!
